language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn build
  - rm -rf src .prettierrc .nvmrc .gitignore node_modules .travis.yml tsconfig.json
deploy:
  provider: npm
  email: kristian.zuffa@gmail.com
  skip_cleanup: true
  api_key:
    secure: PxbUCVIwhTrxycQPh6DmztS9+xdn+Eu8ymXNXKfE8kc6DlgDA6Hc0UdFgMd/7zMuAfVoWjo5+lB+1IA9Fhy/Jd/Tln+0VmqPdXgj0a3Gla5RkcuplbiMLQbvCOo5NygofQVOFcW9XYU1stRNQrTYr4fjoc3qHnof9kKRLKqM/b7xyhyUaDFiNP/ruo51cZBtzT8hy7sm6XkK0MYmy0SbJD6U7eE4gy6KbP+BBUFrNPQ4jBY0hJlyOfEG3SjG65Ws3PWeJ1eHguwQWQRjTQoB8er0oloTAlKsoEZ3iGNvpW2Vf0V4NGme/vP3sKvegMRIkJcBDp9um11uY6plccxFNpxDPtwQXq1NRweRkWCU5E+HL3H4mfj2wR1mEYSOyu8Wi/5ROLa4Mrk11R732/IEReo/S2B0/l/PDJFh1rj/lypwP5M3cSIDtv3GZVKrv/AIK2Gm4eFUzwRxaT6n7WrpdPnztL6IaLa8uAtB0zed0wmM9bqjzgYIF2mXGnWRXmAU1dpbAXYbk5oE2H5yN8tit2HkHZx7+hCTMS5Cd1EN+HBDHVJMRdGVUd80jtlbnAD7iQm+n6pindT4C8YIKIkc8arX5da5Fwts/tPl0zp4codo/4U0GHfiyr82zAWkzOU7hGTw2vXudcUV89dWrjoQy8MJttfJD4pjezPVIV9Ww3w=
  on:
    repo: zuffik/mailtrap-client
    branch: master

branches:
  only:
    - master
