language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn build
  - rm -rf src .prettierrc .nvmrc .gitignore node_modules .travis.yml tsconfig.json
deploy:
  provider: npm
  email: kristian.zuffa@gmail.com
  skip_cleanup: true
  api_key:
    secure: lutXt4yQN8IqFN1eF52ViCZ6uGKBD9i+KmAl1LT6uC2MEDxPuTzyZXU6RmPkmh0PcQEHsLhjOwgwqYgbl3UD4+QwDIUdEPw9YYEUl3luiFjJ9ahJTzArrFJACGK0DchacFPFGR+Vg7aJigjQOQkTkUjKdJpb6HO3YiZwFaA/pNq9o1GrGdLmDsjeC6cnVXE6CGWEbpIvi1RjPIwIeiYcm1F12H58wFV21MVwHxLp/gUkLHBFjVf7+oAogJylZ9B5WW14CLkcpU1SIsL9B3Na81xsSDY66R23fmtRepFAR8WuRRU+7HXoYbmPV+rAMc0qnhGMD7HVg+GjzEh9xwlmBi57oqEmSHuKpyjDXolIEr05c+sygo4lSnLdWrUdAjZ6WfIMNINy3myGi84Q030MGrrMBiJ842MLttll/ZOGp2NdP79kBkNC/TZAzzQzCdRtpCXEKnwsS2tlKVD/aCUdjtu5eCP++g+ojjOFt1FD1EqeKSQUW+3iDz88cQKegTTM6YUuvetEsjU8/vFLNox4P2vNEBgxOKxNpRRgZVWDxc8HSog+WBqWEeQRPr5oUtjIQMrprfwWfc4C9gWh1huyO7XH5iyu5dbxL3wDW18dfBJIteS4wu7jbQYD146YswYsvUEzPRE2Qs8rA0aq8NVa7P+0zGpPl6Zum4y2D2st5VU=
  on:
    repo: zuffik/mailtrap-client
    branch: master

branches:
  only:
    - master
