language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn build
  - rm -rf src .prettierrc .nvmrc .gitignore
    node_modules .travis.yml make-executable.js tsconfig.json
deploy:
  provider: npm
  email: kristian.zuffa@gmail.com
  skip_cleanup: true
  api_key:
    secure: Wj2j/leYM1efp1oUUXpmEoYvQQsM36ivMjBYR4+XOx1oEBhCJARnC2ykiRyhlsRuWZO4mxrLjondO5W7H4mNgnctcqdORzloPNclLPCe1J4/S8OzzFoEsR+cejXqE9GvtHEUo+56j/AotUk9qv3ZpuRj3lS6cjsDBHkN1EfAiqETDTEy/iBHlkr8egYvQk4ueE2WbWSD+O1zW4jg89laNZQ0HvdQ6YUt2MbwbhzDEWxJbVlk3Wo7os4SaVjkJeOINux1iBbSrG+qIhybdn85KnhuNlHHtbsumB4x800MJW+7hYQqCnuuEYlrtO68ctgMr8vihPUD+VuC3TwWyKJ38r3ClRq3yE2kJJedGx7NRvYevukjxf4pvYhirdCzNlIjUOlz+6M8iJT427a7nJ2ojdGa4l3NvauTgvrQnDS/uBCjPC30Cl38EEkdTQ9tLs9umdDgQVjxvKQ0W4h8lv5X1TszUBBWUJRCqhIEAfn6fOJwJa4GtP0H+6dlIFgAxSXGewOvJsOxexp0keorhVCUo+5xt7BehW2f9GXKTaBpmyulmszzJXIcfBy2RUhPeKZ+993WUaXcQwPiwq/YkF9MSkCUVC+z71+Hn9iYdOHHu1qamLhUDeiyuug4RThnaxqxjhtEZ3g7WiOJZPy2xKibnP9UOfdTdhB2/40zYYQEBU0=
  on:
    repo: zuffik/mailtrap-client
    branch: master

branches:
  only:
    - master
